language: cpp

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" GCOV=gcov-7
before_install: eval "${MATRIX_EVAL}"

before_script: mkdir build && cd "$_"
script: cmake -DTEST_COVERAGE=ON .. && make && make test

after_success: bash <(curl -s https://codecov.io/bash) -x "${GCOV}"
